frontend/.eslintignore
frontend/js/actions/alerts.js
frontend/js/app.jsx
frontend/js/components/LocationFilter.jsx
frontend/js/epics/alerts.js
frontend/js/plugins/EarlyWarning.jsx
frontend/js/reducers/alerts.js
frontend/js/utils/AlertsUtils.js

Hazard, levels and events are now in sequential order.
Fixed levels filter and region filter
Fixed text search to use title__contains
Added loading spinner

closes #47, closes#48

---

frontend/css/decat.css
frontend/js/plugins.js
frontend/js/plugins/RightTOCPanel.jsx
frontend/prod-webpack.config.js
frontend/static/decat/localConfig.json
frontend/webpack.config.js

Added RightTOCPanel plugins that move toc from drawer menu to right panel.

Closes #22

---

frontend/css/decat.css
frontend/js/components/EventEditor.jsx
frontend/js/utils/AlertsUtils.js

GeoNode Error messages are now formatted in human-readable format.
In AlertsUtils flattenErrors function, flats errors and returns an array of errors object with title and text properties

Closes #35!

---

frontend/js/app.jsx
frontend/static/decat/localConfig.json

Configured axios to remove CSRFToken from request header, when url contains /geoserver/

Removed CSRFToken from geoserver requests

---

frontend/js/components/EventEditor.jsx
frontend/js/components/Events.jsx
frontend/js/components/LocationFilter.jsx
frontend/js/components/MultiValueFilter.jsx
frontend/js/components/TimeFilter.jsx
frontend/js/epics/alerts.js
frontend/js/plugins/EarlyWarning.jsx
frontend/js/plugins/Header.jsx
frontend/js/plugins/Save.jsx
frontend/js/reducers/alerts.js

Regions resource are  filtered by by point and selected in regions select

Closes #73 and minor fixes for warning

---

frontend/css/decat.css
frontend/js/components/TimeFilter.jsx
frontend/js/plugins.js
frontend/js/plugins/CurrentIntervalFooter.jsx
frontend/js/plugins/EarlyWarning.jsx
frontend/js/plugins/RightTOCPanel.jsx
frontend/static/decat/localConfig.json
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

Move time filter in filter panel, and current time range label on the bottom of the map

Closes #71

---

frontend/css/decat.css
frontend/js/components/LocationFilter.jsx
frontend/js/components/MultiValueFilter.jsx
frontend/js/epics/alerts.js
frontend/js/plugins/CurrentIntervalFooter.jsx
frontend/js/plugins/EarlyWarning.jsx
frontend/js/reducers/alerts.js

Event are updated on filter-change, removed update btn. Closes#87

closes #97

---

frontend/js/epics/GeoNodeConfig.js

Fixed urls

---

frontend/css/decat.css
frontend/js/appConfig.js
frontend/js/epics/GeoNodeConfig.js
frontend/js/ms2override/CatalogUtils.js
frontend/js/reducers/security.js
frontend/js/utils/CSWUtils.js
frontend/js/utils/GeoNodeMapUtils.js
frontend/prod-webpack.config.js
frontend/static/decat/localConfig.json
frontend/webpack.config.js

Metadata Explorers works properly with geonode pyCSW catalogue.
Now It's possible to add layers from geonode catalogue and save the map with added layers

Closes #81, closes#77

---

frontend/js/epics/alerts.js

Changed hours format from 00 - 12 to 00 23

fixed filter timestamp

---

frontend/js/epics/GeoNodeConfig.js
frontend/js/reducers/security.js
frontend/js/utils/CSWUtils.js
frontend/package.json
frontend/webpack.config.js

If user use application default map and has regions setted in data_scope, the map is centred and zoomed to fit data_scope regions bbox.
Also switched axios target url to http://decat-dev.geo-solutions.it

Closes #104

---

frontend/js/actions/GeoNodeConfig.js
frontend/js/actions/alerts.js
frontend/js/appConfig.js
frontend/js/components/EventEditor.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/ms2override/decatDefaultLayers.js
frontend/js/plugins.js
frontend/js/plugins/ZoomOut.jsx
frontend/js/reducers/alerts.js
frontend/js/utils/CSWUtils.js
frontend/js/utils/GeoNodeMapUtils.js

If a user has in one or more regions, configured in data_scope, these are used as map extent constraint.
The check is done in checkMapBbox epic. and is evaluated every time that a change map view action is triggered.
At time of writing data scope isn't working properly and It isn't returning correct regions bbox.

Closes #112

---

frontend/js/components/Card.jsx
frontend/js/components/Events.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/alerts.js
frontend/js/ms2override/ConfigUtils.js
frontend/js/ms2override/decatDefaultLayers.js
frontend/js/plugins.js
frontend/js/plugins/CurrentIntervalFooter.jsx
frontend/js/plugins/DecatDrawer.jsx
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/utils/GeoNodeMapUtils.js
frontend/js/utils/SecurityUtils.js
frontend/static/decat/localConfig.json
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT
frontend/webpack.config.js

Added new plugin for Impact-assessor role.
Added Hazards list, with related filter panel.
Added hazard current and selected layers
Added application switch based on current user role i.e. event-operator -> plugin EarlyWarning, impact-assessor -> Plugin ImpactAssessment and defaultLayers managment
Added a minor fix for max extent constraint.

Issue#94#95

---

frontend/css/decat.css
frontend/js/actions/impactassessment.js
frontend/js/components/Hazard.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/reducers/impactassessment.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT
frontend/webpack.config.js

Added Impact assessment panel. At time of writing assessments are simulated loading map list.
We'll have to fix endpoint and to adapt to real data when /api/assessments/ service will be ready.

Closes #96

---

frontend/css/decat.css
frontend/js/epics/GeoNodeConfig.js
frontend/js/ms2override/ConfigUtils.js
frontend/js/plugins/Save.jsx
frontend/js/plugins/SaveAs.js
frontend/js/utils/GeoNodeMapUtils.js
frontend/static/decat/config.json

If deafault map is missing, client loads map form config.json.
Added new style for promoted and archived!

Closes #121

---

frontend/css/decat.css
frontend/js/actions/alerts.js
frontend/js/actions/impactassessment.js
frontend/js/components/Hazard.jsx
frontend/js/components/ImpactAssessment.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/plugins/Save.jsx
frontend/js/plugins/SaveAs.js
frontend/js/reducers/impactassessment.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT
frontend/webpack.config.js

Added create and save new asswssment from base map or assessment's map.
Added basic inplementation of promote assessment

Closes #128

---

frontend/js/actions/impactassessment.js
frontend/js/components/ImpactAssessment.jsx
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/reducers/impactassessment.js
frontend/webpack.config.js

Added models panel: a paginated list of models with hazard filtering.
Added action epics and reducer to load and filter models.

Closes #99

---

frontend/css/decat.css
frontend/js/actions/impactassessment.js
frontend/js/components/Model.jsx
frontend/js/components/Run.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/plugins/RightTOCPanel.jsx
frontend/js/reducers/impactassessment.js
frontend/js/utils/GeoNodeMapUtils.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT
frontend/webpack.config.js

It adds:
Add uploaded run layer to assessment.
Link to geonode edit layer
fixed model filter bug
Add documents section to toc
Fixed bug in add new run epic

AddLayer and more

---

frontend/css/decat.css
frontend/js/actions/impactassessment.js
frontend/js/components/FilesUpload.jsx
frontend/js/components/InputsPanel.jsx
frontend/js/components/Model.jsx
frontend/js/components/Run.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/ms2override/ConfigUtils.js
frontend/js/ms2override/TitleSubTitle.jsx
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/plugins/RightTOCPanel.jsx
frontend/js/reducers/impactassessment.js
frontend/js/utils/GeoNodeMapUtils.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT
frontend/webpack.config.js

It integrates documents in assessment. It's possible to add to map save map and reload.
Add also minor fixes
With this pull request the assessment management cycle is completed (brgm cases excluded)

Documents integration, Closes #133

---

frontend/css/decat.css
frontend/js/actions/impactassessment.js
frontend/js/components/ErrorModal.jsx
frontend/js/components/Model.jsx
frontend/js/components/Run.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/ms2override/ConfigUtils.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/plugins/RightTOCPanel.jsx
frontend/js/reducers/impactassessment.js
frontend/js/utils/GeoNodeMapUtils.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

Added brgm process, the launch of brgm process doesn't freeze the ui. 
An epics updates wps process status with 30 seconds interval. The epics is killed when user choses a differnet model or loads  different runs and is restored for the running processes when new runs  are loaded.
Wps errors are shown in the run component, while process launch errors are show in a modal.
It's now possible to add to map and svae map whit brgm layers

Brgm porcess, add to map and save brgm layers

---

frontend/js/actions/alerts.js
frontend/js/components/ImpactAssessment.jsx
frontend/js/components/InputsPanel.jsx
frontend/js/components/Model.jsx
frontend/js/components/Run.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/js/reducers/alerts.js

Model list panel height
Input panel height
Close model accordion on new run
Error on new assessment save if default map missing

Various fixes

---

frontend/js/actions/alerts.js
frontend/js/actions/emergencymanager.js
frontend/js/app.jsx
frontend/js/components/EditCop.jsx
frontend/js/components/Hazard.jsx
frontend/js/epics/GeoNodeConfig.js
frontend/js/epics/alerts.js
frontend/js/epics/impactassessment.js
frontend/js/ms2override/Store.js
frontend/js/ms2override/decatDefaultLayers.js
frontend/js/plugins.js
frontend/js/plugins/CurrentIntervalFooter.jsx
frontend/js/plugins/DecatDrawer.jsx
frontend/js/plugins/EmergencyManager.jsx
frontend/js/plugins/RightTOCPanel.jsx
frontend/js/reducers/impactassessment.js
frontend/js/utils/AlertsUtils.js
frontend/js/utils/SecurityUtils.js
frontend/static/decat/localConfig.json
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

It implements emrgency-manager plugin. Missing the part for editing annotation.
With this pull when a user exit from the editing of a cop or of an assessment, the store is restored to the current state before editing was started.

Partially close 175 missing annotation

---

frontend/js/components/Hazard.jsx
frontend/js/plugins/Save.jsx
frontend/js/plugins/SaveAs.js
frontend/js/utils/AlertsUtils.js

Removed save and save as when in emergency mode.
Removed confirmation request to edit cop annotation.
Fixed error parsing

Improved emergency-manager plugin

---

frontend/js/actions/emergencymanager.js
frontend/js/epics/impactassessment.js
frontend/js/plugins/EmergencyManager.jsx
frontend/js/reducers/impactassessment.js
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

Also fixes #232 remaining issues

Fixes #225: warning on cop editing when the mapId is not current anymore

---

frontend/js/actions/impactassessment.js
frontend/js/components/Hazard.jsx
frontend/js/epics/impactassessment.js
frontend/js/plugins/ImpactAssessment.jsx
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

Added a trash bin icon to delete not promoted assessment

Fixes #222 Should be possible to delete non-promoted Impact Assessments

---

decat_geonode/static/decat/translations/data.en-US
decat_geonode/static/decat/translations/data.it-IT
frontend/static/decat/translations/data.en-US
frontend/static/decat/translations/data.it-IT

fix Emergency Management title typos

---

frontend/js/plugins/Annotations.jsx

Fixes #320 Add more icons
